### PR TITLE
Implemented the basic of a HttpClient class for HttpRequest

### LINKED ISSUE #1: [Feature]: Implement HttpClient class
### 🚀 Feature Proposal

The `HttpClient` class will be responsible to make http requests to other services. With this class, we should be able to define global settings to use in all requests that use the `HttpClient` class. This global settings will be based in [`HttpClientBuilder`](https://javadoc.io/doc/org.apache.httpcomponents.client5/httpclient5/5.0.1/index.html) of [Apache](https://www.apache.org/), and we should be able to set a global instance of this builder for all `HttpClient` or create another instance of `HttpClient` using different `HttpClientBuilder` instances.

### Motivation

Nowadays in Athenna if the developer needs to make any Http request he will need to use the vanilla [http](https://nodejs.org/api/http.html) or [https](https://nodejs.org/api/https.html) of [Node.js](https://nodejs.org/en/) or some library like [axios](https://www.npmjs.com/package/axios) or [node-fetch](https://www.npmjs.com/package/node-fetch). It would be nice if Athenna has her own implementation to do that.

### Example

_No response_

### PR DESCRIPTION
**Pull request by RobsonTrasel**
## Proposed changes

Describe the big picture of your changes here to communicate to the
maintainers why we should accept this pull request. If it fixes a bug
or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to ask.
We're here to help! This is simply a reminder of what we are going to look
for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/AthennaIO/Common/blob/master/CONTRIBUTING.md) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

## Further comments

Closes #1

### CODE REVIEW

**Comment by jlenon7** [comment]
I think it would be better to use the [got](https://www.npmjs.com/package/got) library instead of `http` package to do this task @RobsonTrasel. We are going to save a lot of time because this library already implements all this thinks:

Screenshot from 2022-12-16 09-46-41

**Comment by RobsonTrasel** [comment]
Ok, I'll be fixing this.

**Comment by RobsonTrasel** [comment]
I made the requests using `got` libray, but the tests only the `GET `method pass because the other methods needs a paramethers in body. But it just change the paramethers for test the others methods.

**Comment by RobsonTrasel** [comment]
image
There is a image for the log of tests

**Comment by RobsonTrasel** [comment]
Tests will not run because the paramether os my tests are wrong, idk the parameters and the url of your api for tests

**Comment by jlenon7** [comment]
Could you give me permission to commit in your [fork](https://github.com/RobsonTrasel/Common)? @RobsonTrasel 

Screenshot 2022-12-16 at 19 42 58

Check this [tutorial](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) from GitHub of how to give me the permission.

**Comment by RobsonTrasel** [comment]
> Could you give me permission to commit in your [fork](https://github.com/RobsonTrasel/Common)? @RobsonTrasel
> 
> Screenshot 2022-12-16 at 19 42 58
> 
> Check this [tutorial](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) from GitHub of how to give me the permission.

This option it's enabled: 
image

**Pull request merged**
