### PR TITLE
HttpClient and FakeApi helper implementation

### LINKED ISSUE #1: [Feature]: Implement HttpClient class
### 🚀 Feature Proposal

The `HttpClient` class will be responsible to make http requests to other services. With this class, we should be able to define global settings to use in all requests that use the `HttpClient` class. This global settings will be based in [`HttpClientBuilder`](https://javadoc.io/doc/org.apache.httpcomponents.client5/httpclient5/5.0.1/index.html) of [Apache](https://www.apache.org/), and we should be able to set a global instance of this builder for all `HttpClient` or create another instance of `HttpClient` using different `HttpClientBuilder` instances.

### Motivation

Nowadays in Athenna if the developer needs to make any Http request he will need to use the vanilla [http](https://nodejs.org/api/http.html) or [https](https://nodejs.org/api/https.html) of [Node.js](https://nodejs.org/en/) or some library like [axios](https://www.npmjs.com/package/axios) or [node-fetch](https://www.npmjs.com/package/node-fetch). It would be nice if Athenna has her own implementation to do that.

### Example

_No response_

### LINKED ISSUE #5: [Feature]: Implement FakeApi class
### 🚀 Feature Proposal

The `FakeApi` class will be responsible for creating fake, but not totally fake, endpoints using [fastify](https://www.fastify.io/). This class should have an enjoyable API to create new endpoints, it should be very easy to create endpoints that return the following specific data in the response:

- body
- headers
- status code

It would be very nice if `FakeApi` helper could be configured using `.json` files, the same way that [Wiremock](https://wiremock.org/) does. Let's suppose that we have created the `resources/fakeapi/create-user.json` file:

When calling the `await FakeApi.start()` helper, it should read the `resources/fakeapi` folder and register all the routes inside it. The `create-user.json` content would have the route path, method, status code, headers and body defined for the response:

```json
{
  "path": "/users",
  "method": "POST",
  "statusCode": 201,
  "headers": {
    "Content-Type": "application/json"
  },
  "body": {
    "id": 1,
    "name": "Robson Trasel"
  }
}
```

### Motivation

Sometimes the developer needs to create more realistic tests, where he really needs to make a Http request. We have tryed to use [Wiremock](https://wiremock.org/) for this purpose, but is very hard to configure it for Node.js inside pipelines like [Github Actions](https://github.com/features/actions).

### Example

Here is an example of using the `FakeApi` helper API in runtime:

```js
const path = '/users'
const statusCode = 200
const user = { id: 1, name: 'João Lenon' }
const arrayOfUsers = [user]
const headers = {
  Content-Type: 'application/json'
}

await FakeApi.builder()
    .method('GET')
    .path(path)
    .statusCode(statusCode)
    .body(arrayOfUsers)
    .headers(headers)
    // Register the fake route and clear FakeApi static state:
    .register()

const port = 8080

await FakeApi.start(port)

// Requesting to the endpoint we have created:
const users = await HttpClient.get('http://localhost:8080').json()

// Stop the fake server:
await FakeApi.stop()
```

### PR DESCRIPTION
**Pull request by RobsonTrasel**
## Proposed changes

Implementation of `HttpClient` and `FakeApi` helpers.

More details can be found in issues #1 and #5

## Types of changes

What types of changes does your code introduce?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to ask.
We're here to help! This is simply a reminder of what we are going to look
for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/AthennaIO/Common/blob/master/CONTRIBUTING.md) documentation
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] I have added necessary documentation (if appropriate)

## Further comments

Closes #1 
Closes #5

### CODE REVIEW

**Comment by RobsonTrasel** [comment]
Reopened @jlenon7 !!

**Comment by jlenon7** [comment]
I think we can create a new helper too. The `FakeApi` helper to generate "fake" but not totally fake endpoints. What do you think?

**Comment by RobsonTrasel** [comment]
Yes, I will finish the "to do" part and move on to this issue of the Helper for the FakeAPI.

**Comment by jlenon7** [comment]
Right, let the `FakeApi` helper with me, focus on the `HttpClient` and `HttpClientBuilder` classes implementation. If you need any help, let me know.

**Comment by RobsonTrasel** [comment]
I will finish these implementations as soon as possible!

**Comment by RobsonTrasel** [comment]
Added all the methods, from got library. I'll be prepared for the nexts tasks :D

**Review by RobsonTrasel — COMMENTED** [review]
It is in the standard design but I think I can improve the organization to make it a little cleaner to look at. After possible approval, I think I can refactor some methods and make it clearer.

**Comment by jlenon7** [comment]
No problem, I can do that. Do you know how to configure the ESLint in your IDE to run when you save your code?

**Comment by jlenon7** [comment]
I extremely recommend you to use JetBrains IDE's. I use IntelliJ Ultimate, JetBrains has given me the free open source license for all JetBrains IDE's, maybe you can take one too, take a look [here](https://www.jetbrains.com/community/opensource/#support) and check if you fit.

**Comment by jlenon7** [comment]
VSCode does not support ESM right now, you can't see the types of your imports when using ESM import aliases there:

Screenshot 2022-12-20 at 11 06 20

But in IntelliJ this work perfectly fine:

Screenshot 2022-12-20 at 11 07 02

**Comment by RobsonTrasel** [comment]
I thought IntelliJ was only for Java, I will take a look at this IDE.

**Comment by jlenon7** [comment]
It was, but they updated IntelliJ to IntelliJ Ultimate, that works for almost all languages. But the free IDE IntelliJ Community is still working only for Java development.

**Comment by RobsonTrasel** [comment]
Do you have a task that I can be helping with?

**Comment by jlenon7** [comment]
Yes, now we will need to implement tests for all methods of `HttpClient` and `HttpClientBuilder` classes to validate that everything is working. I will finish the implementation of `FakeApi` class, so we can move forward with the tests implementation.

**Comment by jlenon7** [comment]
The `FakeApi` class is done. Now we just need to add tests for `HttpClient` and `HttpClientBuilder` and then open a new PR in [AthennaIO/Docs](https://github.com/AthennaIO/Docs) to add documentation for these three new helpers.

I've already created the [issue to update the docs](https://github.com/AthennaIO/Docs/issues/7), so we don't forget. But for now let's focus on finalizing the tests because the implementation may end up changing as tests go by.

**Pull request merged**
